### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [jroddev/android-oss-release-tracker#6]

**Comment by jroddev** [comment]
Sure thing @Artem13327 
This PR may be relevant for F-Droid
https://github.com/jroddev/android-oss-release-tracker/pull/7

**Comment by jroddev** [comment]
Package Name: com.jroddev.android_oss_release_tracker
App Name: Android OSS Release Tracker
[Short Name](https://github.com/jroddev/android-oss-release-tracker/blob/dd44d100b76b55d3c1c2472de064046f4355d13a/app/src/main/res/values/strings.xml): OSS Tracker

The App Name is quite long, which is why I set the short name to make its icon a bit cleaner.

**Comment by jroddev** [comment]
IzzyOnDroid is referring to it as [OSS Tracker](https://apt.izzysoft.de/fdroid/index/apk/com.jroddev.android_oss_release_tracker).
I'm fine with either.

**Comment by jroddev** [comment]
Can I modify it later? For now just the github url should be enough.

**Comment by jroddev** [comment]
That should be fine.
If you haven submitted yet the email you can use is jroddev@gmail.com

**Comment by jroddev** [comment]
author: `jroddev`

**Comment by IzzySoft** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12125 to follow up (I've copied most of the metadata from my repo). Let's see if it builds and all pipelines succeed (yay, just waiting for the build now, all other pipelines **did** succeed) :smiley:

**Comment by IzzySoft** [comment]
Build succeeded. Now it's waiting for a review before entering the final state (merge and going into the build cycle to be published).

That said: The app is currently in my repo. Shall it (for some reason) remain there after it becomes available at F-Droid.org? Usually I remove an app after a decent overlap of 10..14 days unless explicitly requested otherwise. @jroddev please let me know in time if you want it to stay – I will then link to your answer for those looking for the "why" (or remove it as described, depending on your answer). Thanks!

**Comment by jroddev** [comment]
@Artem13327 @IzzySoft  looks good to me. Do you need any action from me on that MR or is my thumbs up here enough?

**Comment by jroddev** [comment]
@IzzySoft I'm happy for the application to stay listed in your repository, but it's up to you (your repository). 
The one thing to consider is that if you're using the releases directly from GitHub they will be signed with my keys. If a user tries to update to a version from f-droid it will fail because those builds are signed with f-droid keys.
Users will need to uninstall one version before reinstalling the other.
They will need to export/import to retain their tracking list (luckily this feature was added in [0.1.4](https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.4)

**Comment by IzzySoft** [comment]
> The one thing to consider is that if you're using the releases directly from GitHub they will be signed with my keys. If a user tries to update to a version from f-droid it will fail because those builds are signed with f-droid keys.

Being one of the F-Droid maintainers, that's clear to me – and one of the reasons I usually remove apps at that stage (with congrats to their team for having reached those "higher echelons"). OTOH, that might be exactly the reason why some want it to stay, so their existing PlayStore-Users can easily "move over" to a more privacy-friendly place (the other reason with the update frequency became more redundant since F-Droid switched to the new build servers and updates take between 2..3 days on average instead of 5..7 days – I might need to update [my corresponding wiki page](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)).

> They will need to export/import to retain their tracking list

Oh, there is an easy update path – so switching is as easy as export, uninstall, reinstall, import? Is everything needed covered that way? In that case I'd indeed suggest to rather remove it at my end, to avoid the confusion described.

I leave the final say to you then.

> Do you need any action from me on that MR

No, not necessarily. I've linked here for "proof" that you've been informed and do not object (in fact rather support) inclusion. It now just needs an F-Droid team member to review the app. I could do that myself of course (and probably will if nobody else does within the next days and I find time to perform the review).

Thanks a lot for your support, considerations and thoughtfulness!

**Comment by linsui** [comment]
There are some files (baseline.prof, baseline.profm and classes.dex) in the apk built by us different from yours. Do you want to try to make it reproducible? I don't know why those files are different though. https://f-droid.org/docs/Reproducible_Builds/ may help.

**Comment by jroddev** [comment]
Could be a different version of gradle, build tools, or something similar? I'm not too sure.
I'm also building directly through Android Studio `Build/Generate Singed Bundle / APK` on Manjaro Linux, instead of through CI.

**Comment by jroddev** [comment]
@linsui  In [0.1.5](https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.5) I have applied the Android Studio recommended updates and reduced minSdk to 27. I'm not sure why, but the new version is 30% the file size it was previously. Perhaps this new version helps with the reproducibility? - Flying a bit blind here so it may be worth a shot.

**Comment by linsui** [comment]
This version is more reproducible, thanks! It still suffers from an issue: https://issuetracker.google.com/issues/231837768

I built it 4 times and got the same results twice. It may takes more cycles to be published if we enable reproducible build. Do you want to enable it?

**Comment by linsui** [comment]
Ah, I megerd it by mistake... Let's see if it can be build in the next cycle. Could you please change the apk name in the release? With the data in the name we can't automatically fetch the apk.

**Comment by linsui** [comment]
Anyway, it builds reproducibly. https://monitor.f-droid.org/builds/log/com.jroddev.android_oss_release_tracker/6#site-footer Maybe we are too lucky.

**Comment by jroddev** [comment]
@linsui what is the renaming for? Is it just so that f-droid picks up something is different?

**Comment by obfusk** [comment]
@jroddev automatic updates can only use the version name/code (`%v`/`%c`) when generating the URL, they don't have a way of knowing the release date.

So the current URL `https://github.com/jroddev/android-oss-release-tracker/releases/download/0.1.5/android-oss-release-tracker-release-2022-12-03.apk` doesn't work for the next version.

But without the date in the filename we can use e.g. `https://github.com/jroddev/android-oss-release-tracker/releases/download/%v/android-oss-release-tracker-release.apk`, which does.

Using the version name/code in the filename would of course also be fine.

**Comment by jroddev** [comment]
@obfusk I have added `android-oss-release-tracker-release-v0.1.5.apk`. Does that work?

**Comment by linsui** [comment]
Yes, that works. Thanks!

**Comment by obfusk** [comment]
@jroddev since your app has now been published :tada:, you may want to add a "get it on F-Droid" badge to your README :)

**Comment by IzzySoft** [comment]
That said, please also let me know if I shall keep your app in my repo. I usually remove apps here 10..14 days after they reached F-Droid unless keeping them was explicitly requested.

**Comment by jroddev** [comment]
@IzzySoft happy for you to remove from your repo.
Thank you everyone for your help on this one
